/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import java.io.ByteArrayInputStream;

import static org.testng.Assert.*;

public class AppTest {

    @DataProvider(name="names")
    public Object [][] names() {
            return new Object [][] {
                    {"Steven"},
                    {"Sara"}
            };
    }

    @Test(dataProvider = "names")
    public void appHasAGreeting(String expectedName) {
        // given
        App app = new App();
        System.setIn(new ByteArrayInputStream(expectedName.getBytes()));

        // when
        String name = app.readName();

        // then
        assertEquals(name, expectedName);
    }


}
